//
// RoomInviteRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomInviteRequest: Codable {

    public var playerId: String
    public var roomId: String
    public var playerIds: [String]

    public init(playerId: String, roomId: String, playerIds: [String]) {
        self.playerId = playerId
        self.roomId = roomId
        self.playerIds = playerIds
    }


}
