//
// RoomJoinRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoomJoinRequest: Codable {

    public var playerId: String
    public var roomId: String

    public init(playerId: String, roomId: String) {
        self.playerId = playerId
        self.roomId = roomId
    }


}
