//
// TestnetMintRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TestnetMintRequest: Codable {

    public var playerId: String
    public var isType: String

    public init(playerId: String, isType: String) {
        self.playerId = playerId
        self.isType = isType
    }


}
