//
// XummReturnUrl.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummReturnUrl: Codable {

    public var app: String?
    public var web: String?

    public init(app: String? = nil, web: String? = nil) {
        self.app = app
        self.web = web
    }


}
