//
// XummUserToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummUserToken: Codable {

    public var userToken: String
    public var tokenIssued: String
    public var tokenExpiration: String

    public init(userToken: String, tokenIssued: String, tokenExpiration: String) {
        self.userToken = userToken
        self.tokenIssued = tokenIssued
        self.tokenExpiration = tokenExpiration
    }

    public enum CodingKeys: String, CodingKey { 
        case userToken = "user_token"
        case tokenIssued = "token_issued"
        case tokenExpiration = "token_expiration"
    }

}
