//
// XummSigninRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummSigninRequest: Codable {

    public var playerId: String
    public var payloadId: String

    public init(playerId: String, payloadId: String) {
        self.playerId = playerId
        self.payloadId = payloadId
    }


}
