//
// XummSigninResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummSigninResponse: Codable {

    public var address: String
    public var userToken: String

    public init(address: String, userToken: String) {
        self.address = address
        self.userToken = userToken
    }


}
