//
// XummWebhookRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummWebhookRequest: Codable {

    public var meta: XummMeta
    public var customMeta: XummCustomMeta
    public var payloadResponse: XummWebhookPayload
    public var userToken: XummUserToken

    public init(meta: XummMeta, customMeta: XummCustomMeta, payloadResponse: XummWebhookPayload, userToken: XummUserToken) {
        self.meta = meta
        self.customMeta = customMeta
        self.payloadResponse = payloadResponse
        self.userToken = userToken
    }

    public enum CodingKeys: String, CodingKey { 
        case meta
        case customMeta = "custom_meta"
        case payloadResponse
        case userToken
    }

}
