//
// XummCustomMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummCustomMeta: Codable {

    public var identifier: String?
    public var blob: XummCustomBlob
    public var instruction: String?

    public init(identifier: String? = nil, blob: XummCustomBlob, instruction: String? = nil) {
        self.identifier = identifier
        self.blob = blob
        self.instruction = instruction
    }


}
