//
// XummMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummMeta: Codable {

    public var url: String
    public var applicationUuidv4: String
    public var payloadUuidv4: String
    public var openedByDeeplink: Bool

    public init(url: String, applicationUuidv4: String, payloadUuidv4: String, openedByDeeplink: Bool) {
        self.url = url
        self.applicationUuidv4 = applicationUuidv4
        self.payloadUuidv4 = payloadUuidv4
        self.openedByDeeplink = openedByDeeplink
    }

    public enum CodingKeys: String, CodingKey { 
        case url
        case applicationUuidv4 = "application_uuidv4"
        case payloadUuidv4 = "payload_uuidv4"
        case openedByDeeplink = "opened_by_deeplink"
    }

}
