//
// XummOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummOptions: Codable {

    public var submit: Bool
    public var expire: String
    public var returnUrl: XummReturnUrl

    public init(submit: Bool, expire: String, returnUrl: XummReturnUrl) {
        self.submit = submit
        self.expire = expire
        self.returnUrl = returnUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case submit
        case expire
        case returnUrl = "return_url"
    }

}
