//
// XummIssuedAmount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummIssuedAmount: Codable {

    public var currency: String
    public var issuer: String
    public var value: String

    public init(currency: String, issuer: String, value: String) {
        self.currency = currency
        self.issuer = issuer
        self.value = value
    }


}
