//
// XummTxJson.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummTxJson: Codable {

    public var transactionType: String
    public var amount: XummIssuedAmount?
    public var limitAmount: XummIssuedAmount?
    public var fee: String?
    public var destination: String?

    public init(transactionType: String, amount: XummIssuedAmount? = nil, limitAmount: XummIssuedAmount? = nil, fee: String? = nil, destination: String? = nil) {
        self.transactionType = transactionType
        self.amount = amount
        self.limitAmount = limitAmount
        self.fee = fee
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey { 
        case transactionType = "TransactionType"
        case amount = "Amount"
        case limitAmount = "LimitAmount"
        case fee = "Fee"
        case destination = "Destination"
    }

}
