//
// XummPayloadResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct XummPayloadResponse: Codable {

    public var payloadId: String

    public init(payloadId: String) {
        self.payloadId = payloadId
    }


}
