//
// RoomAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class RoomAPI {
    /**
     Invite a player to the room

     - parameter body: (body) Player ID to add to the room 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roomInvite(body: RoomInviteRequest, completion: @escaping ((_ data: MessageResponse?,_ error: Error?) -> Void)) {
        roomInviteWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Invite a player to the room
     - POST /room/invite
     - 

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "code" : 0,
  "type" : "type",
  "message" : "message"
}}]
     - parameter body: (body) Player ID to add to the room 

     - returns: RequestBuilder<MessageResponse> 
     */
    open class func roomInviteWithRequestBuilder(body: RoomInviteRequest) -> RequestBuilder<MessageResponse> {
        let path = "/room/invite"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MessageResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Join a room

     - parameter body: (body) Player ID who joined the room 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roomJoin(body: RoomJoinRequest, completion: @escaping ((_ data: MessageResponse?,_ error: Error?) -> Void)) {
        roomJoinWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Join a room
     - POST /room/join
     - 

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "code" : 0,
  "type" : "type",
  "message" : "message"
}}]
     - parameter body: (body) Player ID who joined the room 

     - returns: RequestBuilder<MessageResponse> 
     */
    open class func roomJoinWithRequestBuilder(body: RoomJoinRequest) -> RequestBuilder<MessageResponse> {
        let path = "/room/join"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MessageResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
