//
// RoundAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class RoundAPI {
    /**
     Submit a new round bet

     - parameter body: (body) Player ID of the round bet owner 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func roundAction(body: RoundActionRequest, completion: @escaping ((_ data: MessageResponse?,_ error: Error?) -> Void)) {
        roundActionWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Submit a new round bet
     - POST /round/action
     - 

     - :
       - type: http
       - name: bearerAuth
     - examples: [{contentType=application/json, example={
  "code" : 0,
  "type" : "type",
  "message" : "message"
}}]
     - parameter body: (body) Player ID of the round bet owner 

     - returns: RequestBuilder<MessageResponse> 
     */
    open class func roundActionWithRequestBuilder(body: RoundActionRequest) -> RequestBuilder<MessageResponse> {
        let path = "/round/action"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<MessageResponse>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
